apiVersion: apps/v1
kind: Deployment
metadata:
  name: jetbrainsai2api-minimal
  labels:
    app: jetbrainsai2api
    variant: minimal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jetbrainsai2api
      variant: minimal
  template:
    metadata:
      labels:
        app: jetbrainsai2api
        variant: minimal
    spec:
      # 全面污点容忍配置 - 能在任何节点调度
      tolerations:
      # 容忍所有可能的污点
      - operator: "Exists"
        effect: "NoSchedule"
      - operator: "Exists"
        effect: "PreferNoSchedule"
      - operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      
      containers:
      - name: jetbrainsai2api
        image: ghcr.io/REPO_OWNER/jetbrainsai2api:1.0.0
        ports:
        - containerPort: 8000
          name: http
        
        # 超低资源配置 - 针对资源极度紧张的环境
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        
        env:
        - name: DEBUG_MODE
          value: "false"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: JWT_TOKEN_1
          valueFrom:
            secretKeyRef:
              name: jetbrainsai-secrets
              key: jwt-token-1
              optional: true
        - name: JWT_TOKEN_2
          valueFrom:
            secretKeyRef:
              name: jetbrainsai-secrets
              key: jwt-token-2
              optional: true
        
        # 简化的健康检查
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
      
      # 重启策略
      restartPolicy: Always
      
      # 终止宽限期
      terminationGracePeriodSeconds: 10